#!/usr/bin/env node
var p=process.env.HIPPOCAMPUS_BINARY||"hippocampus",f=8765,w=10;function h(o){console.log(JSON.stringify(o))}var g="/tmp/hippocampus-cc-plugin.log";function i(o,t){if(process.env.HIPPOCAMPUS_DEBUG==="true")try{let e=require("fs"),n=new Date().toISOString(),s=t?` ${JSON.stringify(t,null,2)}`:"",r=`[${n}] [hippocampus-cc-plugin] ${o}${s}
`;e.appendFileSync(g,r,{encoding:"utf8"})}catch{}}async function y(){return new Promise(o=>{let t="";process.stdin.setEncoding("utf8"),process.stdin.on("data",e=>{t+=e}),process.stdin.on("end",()=>{try{o(t.trim()?JSON.parse(t):{cwd:process.cwd()})}catch{o({cwd:process.cwd()})}})})}function P(o){let t=o.split("/").filter(e=>e&&e!=="opencode");return t.length>0?t[t.length-1]:"default"}async function v(o){try{let t=`${o}/who`,e=new AbortController,n=setTimeout(()=>e.abort(),1e3),s=await fetch(t,{signal:e.signal});if(clearTimeout(n),s.ok)return(await s.json()).service==="hippocampus";let r=`${o}/health`,a=new AbortController,c=setTimeout(()=>a.abort(),1e3),l=await fetch(r,{signal:a.signal});return clearTimeout(c),l.ok?(await l.json()).service==="hippocampus":!1}catch{return!1}}async function S(){let o=process.env.HIPPOCAMPUS_HTTP_URL;if(o)try{let t=new URL(o);return o}catch{return/^\d+$/.test(o)?`http://localhost:${o}/api`:o}for(let t=0;t<w;t++){let n=`http://localhost:${f+t}/api`;try{if(await v(n))return n}catch{}}return null}async function m(){return await S()}async function u(){let o=await m(),t=o!==null;return i("Checking API availability",{available:t,apiBase:o}),t}async function $(){try{let{spawn:o}=require("child_process");i("Starting hippocampus server with setsid",{binary:p});let t=o("setsid",[p,"--http"],{stdio:"ignore",detached:!0});t.unref(),i("Server spawned with setsid",{pid:t.pid}),await new Promise(n=>setTimeout(n,2e3));let e=!t.killed;return i("Server status after 2s",{pid:t.pid,alive:e}),e}catch(o){i("Failed to spawn with setsid",{error:o.message});try{let{spawn:t}=require("child_process");i("Trying fallback spawn without setsid",{binary:p});let e=t(p,["--http"],{stdio:"ignore",detached:!0});e.unref(),i("Server spawned without setsid",{pid:e.pid}),await new Promise(s=>setTimeout(s,2e3));let n=!e.killed;return i("Server status after 2s (fallback)",{pid:e.pid,alive:n}),n}catch(t){return i("Fallback spawn also failed",{error:t.message}),!1}}}async function b(){if(await u())return!0;if(!await $())return!1;await new Promise(t=>setTimeout(t,5e3));for(let t=0;t<10;t++){if(await u())return!0;await new Promise(e=>setTimeout(e,2e3))}return!1}async function A(o){if(!await b())return null;let e=await m();if(!e)return null;try{let[n,s,r]=await Promise.all([fetch(`${e}/list?scope=project&project=${encodeURIComponent(o)}&limit=10`),fetch(`${e}/list?scope=personal&limit=10`),fetch(`${e}/list?scope=global&limit=10`)]),a=[];if(n.ok){let c=await n.json();a.push(...c.memories||[])}if(s.ok){let c=await s.json();a.push(...c.memories||[])}if(r.ok){let c=await r.json();a.push(...c.memories||[])}return i("Fetched memories",{project:o,total:a.length}),a}catch(n){return i("Failed to fetch memories",{error:n.message}),null}}function k(o){if(!o||o.length===0)return"";let t=`<hippocampus_memories>
`;return t+=`**${o.length} memories loaded for this session**

`,o.forEach((e,n)=>{let s=e.scope?` [${e.scope}]`:"",r=e.project?`${e.project}`:e.scope||"global";t+=`**Memory ${n+1}: ${r}**${s} (${e.context})
`,t+=`${e.content}
`,t+=`_Keywords: ${(e.keywords||[]).join(", ")}_

`}),t+="</hippocampus_memories>",t}async function _(){let t=(await y()).cwd||process.cwd(),e=P(t),n=await A(e),s="";n===null?s=`<hippocampus_memories>
\u26A0\uFE0F Could not connect to Hippocampus API. Make sure the MCP server is running.
</hippocampus_memories>`:n.length>0?s=k(n):s=`<hippocampus_memories>
\u{1F4ED} No memories found for project "${e}".
</hippocampus_memories>`,h({hookSpecificOutput:{hookEventName:"SessionStart",additionalContext:s}})}_().catch(o=>{h({hookSpecificOutput:{hookEventName:"SessionStart",additionalContext:`<hippocampus_memories>
\u274C Error: ${o.message}
</hippocampus_memories>`}})});
